[build]
builder = "NIXPACKS"
buildCommand = "yarn install && yarn build"
publishDirectory = "dist"

[deploy]
startCommand = "yarn preview"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 