[build]
builder = "NIXPACKS"
buildCommand = "yarn install --frozen-lockfile && yarn build"
watchPatterns = ["src/**", "public/**"]

[deploy]
startCommand = "yarn preview"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
PORT = "3000" 